server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: metadata_service
          uri: http://localhost:8081
          predicates:
            - Path=/api/metadata/**
        - id: file_service
          uri: http://localhost:8082
          predicates:
            - Path=/api/files/**

# Optional Eureka configuration if you're using service discovery
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/